### ISSUE TITLE
PothosFlow crash when ports change and ProxyBlockEval is in error

### ISSUE THREAD

**Issue by ashley-b** [pothosware/PothosCore#130]
PothosFlow crashes if you have audio source linked to a audio sink for example and have one set to one port per channel, if you set the num channels to 33 so it errors and then go back to a sane value it crashes.
This also happens in a block am working on.

![pothosflow crash](https://user-images.githubusercontent.com/5248379/31119434-c59fcf1c-a87c-11e7-97cb-c514d4c87b81.png)

Backtrace is from current master ee22f4ccd60dbf492aae19cc7c7b32de7054e19c
<pre>
#0  0x00000000004923a5 in Pothos::Proxy::callProxy<>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=this@entry=0x7fff3cff8270, name="inputPortInfo")
    at /pothos/include/Pothos/Proxy/ProxyImpl.hpp:83
#1  0x00000000004ef406 in Pothos::Proxy::call<std::vector<Pothos::PortInfo, std::allocator<Pothos::PortInfo> >>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=this@entry=0x7fff3cff8270, name="inputPortInfo") at /pothos/include/Pothos/Proxy/ProxyImpl.hpp:73
#2  0x00000000004ec2c3 in BlockEval::evaluationProcedure() (this=this@entry=0x7fff6c005700) at /pothos/flow/EvalEngine/BlockEval.cpp:298
#3  0x00000000004ed8c1 in BlockEval::update() (this=0x7fff6c005700) at /pothos/flow/EvalEngine/BlockEval.cpp:138
#4  0x00000000004dcfad in EvalEngineImpl::evaluate() (this=0x11784e0) at /pothos/flow/EvalEngine/EvalEngineImpl.cpp:269
#5  0x00000000004dee89 in EvalEngineImpl::handleMonitorTimeout() (this=<optimized out>) at /pothos/flow/EvalEngine/EvalEngineImpl.cpp:176
#6  0x00000000004fdf6d in EvalEngineImpl::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=<optimized out>, _id=<optimized out>, _a=0x7fff3cff87a0, _c=<optimized out>)
    at /pothos/build/flow/PothosFlow_autogen/2WKBORAYA7/moc_EvalEngineImpl.cpp:139
#7  0x00007ffff4f83a73 in QMetaObject::activate(QObject*, int, int, void**) () at /lib64/libQt5Core.so.5
#8  0x00007ffff4f8fbb8 in QTimer::timerEvent(QTimerEvent*) () at /lib64/libQt5Core.so.5
#9  0x00007ffff4f8488b in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#10 0x00007ffff57a75dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#11 0x00007ffff57aec74 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#12 0x00007ffff4f5c627 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#13 0x00007ffff4faa48b in QTimerInfoList::activateTimers() () at /lib64/libQt5Core.so.5
#14 0x00007ffff4faa9d1 in timerSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#15 0x00007ffff0d56247 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#16 0x00007ffff0d565e8 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#17 0x00007ffff0d5667c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#18 0x00007ffff4faae4f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#19 0x00007ffff4f5b60a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#20 0x00007ffff4db399a in QThread::exec() () at /lib64/libQt5Core.so.5
#21 0x00007ffff4db7c9e in QThreadPrivate::start(void*) () at /lib64/libQt5Core.so.5
#22 0x00007ffff5eb136d in start_thread () at /lib64/libpthread.so.0
#23 0x00007ffff419ebbf in clone () at /lib64/libc.so.6
</pre>

**Comment by guruofquality** [comment]
Thanks for the report, this should do the trick: https://github.com/pothosware/PothosFlow/commit/25b689b8c1790a4a89fb952206667a377920e98c
