### ISSUE TITLE
GCC warning warning: base class ‘struct Pothos::TestingBase’ non-virtual destructor

### ISSUE THREAD

**Issue by ashley-b** [pothosware/PothosCore#141]
Compiling block test code gives this warning
warning: base class ‘struct Pothos::TestingBase’ has accessible non-virtual destructor [-Wnon-virtual-dtor]

**Comment by ashley-b** [comment]
On further inspection I just compiled Pothos with -Wnon-virtual-dtor and there is a few classes that are missing virtual destructors but have virtual methods in there base class.

**Comment by guruofquality** [comment]
Thanks, thats a good thing to check for, fixed in master
