### ISSUE TITLE
PothosGui not displaying added blocks

### ISSUE THREAD

**Issue by lrm11** [pothosware/PothosCore#149]
Hello,
I am trying to add custom blocks to my PothosGui block tree.  These blocks exist on a computer (we'll call it computer A) and are visible in its block tree; I am trying to learn how to add them to a fresh Pothos install on a different computer (computer B).  I found the issue "Problems building a C blocks #79" very helpful but after checking the 3 items guruofquality said to check:  1. Is there a block description comment? Yes; 2. Does the cmake code have ENABLE_DOCS set in the call to POTHOS_MODULE_UTIL()? Yes.; 3. If the module containing your block is loaded properly, you should be able to see it in the plug-in tree by running PothosUtil --plugin-tree=/blocks. Yes my blocks are there in both the /blocks/path/to/my_block, and /blocks/docs/path/to/my_block, I am still not seeing the blocks show up in the PothoGui block tree.  Any further suggestions for where I might be going wrong?

Thanks,
Lara

**Comment by guruofquality** [comment]
Everything sounds correct, especially if you see everything in /blocks/docs/path/to/my_block. Not really sure.

How are you running Pothos GUI? From command line or from a menu? Sometimes command-line shells have different PATH and LD_LIBRARY_PATH stuff set. That could be a reason based on bash profile.

Also, can you check the host explorer panel as well. The same plugin modules should show up there as well. I'm curious if the command line saw this and if its missing in the GUI's plugin module tree: https://github.com/pothosware/PothosFlow/wiki/Tutorial#the-host-explorer-panel
