### ISSUE TITLE
Missing rtl-sdr.rules after "sudo apt-get install libpulse-dev libgtk-3-dev"

### ISSUE THREAD

**Issue by rrobinett** [pothosware/PothosCore#158]
My SDRPlay is 1 hour away, so I thought I would try to use my RTP-SDR dongle with SoapySDRServer, but I get a "usb_open error -3".
I can't find rtl-sdr.rules anywhere in my file system.

===========
pi@pi1-berkeley:~/SoapyRTLSDR/build $ SoapySDRUtil --probe="driver=rtlsdr"
######################################################
######################################################

Probe device driver=rtlsdr
usb_open error -3
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules

----------------------------------------------------
-- Device identification
----------------------------------------------------
  driver=RTLSDR
  hardware=RTLSDR
  origin=https://github.com/pothosware/SoapyRTLSDR
.....

**Comment by guruofquality** [comment]
This is just not the project tracker for rtl library support, its maintained here: https://github.com/osmocom/rtl-sdr/ and that file is in the repo https://github.com/osmocom/rtl-sdr/blob/master/rtl-sdr.rules and if you follow the instructions it talks about setting up udev for source installs http://osmocom.org/projects/sdr/wiki/rtl-sdr
