### ISSUE TITLE
std::atomic<unsigned long long> on 32-bit processor

### ISSUE THREAD

**Issue by wluker** [pothosware/PothosCore#163]
When building using gcc on a zynq processor I had to add -latomic for the linker. I think this is because in lib/util/UID.cpp std::atomic<unsigned long long> is larger than 32-bits.

**Comment by guruofquality** [comment]
It probably had to use a library call since there isnt a native atomic set of instructions for 64-bit. Interestingly, the UID stuff is very casually using it just to make sure its a unique number, nothing special or performant. I'm making a PR to always link atomic when its found.
