### ISSUE TITLE
Feature request: allow wildcards in PothosUtil --self-tests

### ISSUE THREAD

**Issue by ncorgan** [pothosware/PothosCore#185]
If I have a module with the following tests:

/foo/tests/test_takes_a_while
/foo/tests/test_something_unrelated
/foo/tests/test_some_conversion
/foo/tests/test_some_other_conversion

I'd like to be able to call `PothosUtil --self-tests=/foo/tests/test*conversion` and just run the conversion tests.

**Comment by guruofquality** [comment]
https://github.com/pothosware/PothosCore/commit/498ffe569437efcb785d9b127ad01d0558e32eae
