### ISSUE TITLE
Unable to build on Debian Testing due to libpoco not finding PCRE

### ISSUE THREAD

**Issue by n0p** [pothosware/PothosCore#201]
Cmake complained that it could not find PCREConfig.cmake or pcre-config.cmake, from the libpoco installed on the system.

Fixed with
` cmake -DENABLE_INTERNAL_POCO=TRUE`

Did not find anything referencing this on a couple of searches, so I am posting this here for future reference :)

**Comment by guruofquality** [comment]
There is either a libpcre-dev to install or the debian package of libpoco-dev might be missing files.

This isnt a library that Pothos build cares about per say, its just pulling in PocoConfig.cmake and trying to use it. And I guess PocoConfig.cmake is looking for something that isnt there.
