### ISSUE TITLE
ClangCompilerSupport: don't hardcode libc++

### ISSUE THREAD

**Issue by ncorgan** [pothosware/PothosCore#233]
There should be a way at PothosCore build-time to set the linking flag to use libc++ or libstdc++.

**Comment by guruofquality** [comment]
I think you need to link against the same runtime that the core library was linked against. It may have to remember it at cmake configure time for PothosCore

**Comment by ncorgan** [comment]
Yup, that's the plan. This should be simple by checking for one of the `_GLIBCXX_*` defines.

**Comment by guruofquality** [comment]
I dont think I set libstdc anymore in any of the projects, I think this line can just go entirely in the clang build.
